services:
  backend:
    build:
      dockerfile: DockerFile
      container_name: flaskBackend
      volumes:
        -./:/app

    
  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile